// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Name field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Category name
   * - **API ID Path**: category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<"thumbnail"> /**
   * Meta Title field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page title for search engines (max 60 characters)
   * - **API ID Path**: category.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page description for search engines (max 160 characters)
   * - **API ID Path**: category.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OpenGraph Title field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title for social media sharing (defaults to Meta Title if empty)
   * - **API ID Path**: category.og_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_title: prismic.KeyTextField;

  /**
   * OpenGraph Description field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description for social media sharing (defaults to Meta Description if empty)
   * - **API ID Path**: category.og_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_description: prismic.KeyTextField;

  /**
   * OpenGraph Image field in *Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Twitter Card Type field in *Category*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select Twitter card type
   * - **Default Value**: summary_large_image
   * - **API ID Path**: category.twitter_card
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  twitter_card: prismic.SelectField<
    "summary" | "summary_large_image",
    "filled"
  >;

  /**
   * Canonical URL field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Custom canonical URL (optional)
   * - **API ID Path**: category.canonical_url
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  canonical_url: prismic.KeyTextField;

  /**
   * Robots Meta field in *Category*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Search engine indexing
   * - **Default Value**: index,follow
   * - **API ID Path**: category.robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  robots: prismic.SelectField<
    "index,follow" | "noindex,follow" | "index,nofollow" | "noindex,nofollow",
    "filled"
  >;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page title for search engines (max 60 characters)
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page description for search engines (max 160 characters)
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OpenGraph Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title for social media sharing (defaults to Meta Title if empty)
   * - **API ID Path**: homepage.og_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_title: prismic.KeyTextField;

  /**
   * OpenGraph Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description for social media sharing (defaults to Meta Description if empty)
   * - **API ID Path**: homepage.og_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_description: prismic.KeyTextField;

  /**
   * OpenGraph Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Twitter Card Type field in *Homepage*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select Twitter card type
   * - **Default Value**: summary_large_image
   * - **API ID Path**: homepage.twitter_card
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  twitter_card: prismic.SelectField<
    "summary" | "summary_large_image",
    "filled"
  >;

  /**
   * Canonical URL field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Custom canonical URL (optional)
   * - **API ID Path**: homepage.canonical_url
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  canonical_url: prismic.KeyTextField;

  /**
   * Robots Meta field in *Homepage*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Search engine indexing
   * - **Default Value**: index,follow
   * - **API ID Path**: homepage.robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  robots: prismic.SelectField<
    "index,follow" | "noindex,follow" | "index,nofollow" | "noindex,nofollow",
    "filled"
  >;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page title for search engines (max 60 characters)
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page description for search engines (max 160 characters)
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OpenGraph Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title for social media sharing (defaults to Meta Title if empty)
   * - **API ID Path**: page.og_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_title: prismic.KeyTextField;

  /**
   * OpenGraph Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description for social media sharing (defaults to Meta Description if empty)
   * - **API ID Path**: page.og_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_description: prismic.KeyTextField;

  /**
   * OpenGraph Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Twitter Card Type field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select Twitter card type
   * - **Default Value**: summary_large_image
   * - **API ID Path**: page.twitter_card
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  twitter_card: prismic.SelectField<
    "summary" | "summary_large_image",
    "filled"
  >;

  /**
   * Canonical URL field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Custom canonical URL (optional)
   * - **API ID Path**: page.canonical_url
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  canonical_url: prismic.KeyTextField;

  /**
   * Robots Meta field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Search engine indexing
   * - **Default Value**: index,follow
   * - **API ID Path**: page.robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  robots: prismic.SelectField<
    "index,follow" | "noindex,follow" | "index,nofollow" | "noindex,nofollow",
    "filled"
  >;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PostDocumentDataSlicesSlice = never;

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Name field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Post title
   * - **API ID Path**: post.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Featured Image field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<"thumbnail">;

  /**
   * Category field in *Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: post.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;

  /**
   * Publication Date field in *Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Select publication date
   * - **API ID Path**: post.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  publication_date: prismic.DateField;

  /**
   * Excerpt field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief description of the post
   * - **API ID Path**: post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Article Text field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Main article content
   * - **API ID Path**: post.article_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  article_text: prismic.RichTextField;

  /**
   * Slice Zone field in *Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PostDocumentDataSlicesSlice> /**
   * Meta Title field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page title for search engines (max 60 characters)
   * - **API ID Path**: post.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page description for search engines (max 160 characters)
   * - **API ID Path**: post.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OpenGraph Title field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title for social media sharing (defaults to Meta Title if empty)
   * - **API ID Path**: post.og_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_title: prismic.KeyTextField;

  /**
   * OpenGraph Description field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description for social media sharing (defaults to Meta Description if empty)
   * - **API ID Path**: post.og_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_description: prismic.KeyTextField;

  /**
   * OpenGraph Image field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * OpenGraph Type field in *Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Content type
   * - **Default Value**: article
   * - **API ID Path**: post.og_type
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  og_type: prismic.SelectField<"article", "filled">;

  /**
   * Article Author field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Author name for structured data
   * - **API ID Path**: post.article_author
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  article_author: prismic.KeyTextField;

  /**
   * Twitter Card Type field in *Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select Twitter card type
   * - **Default Value**: summary_large_image
   * - **API ID Path**: post.twitter_card
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  twitter_card: prismic.SelectField<
    "summary" | "summary_large_image",
    "filled"
  >;

  /**
   * Canonical URL field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Custom canonical URL (optional)
   * - **API ID Path**: post.canonical_url
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  canonical_url: prismic.KeyTextField;

  /**
   * Robots Meta field in *Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Search engine indexing
   * - **Default Value**: index,follow
   * - **API ID Path**: post.robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  robots: prismic.SelectField<
    "index,follow" | "noindex,follow" | "index,nofollow" | "noindex,nofollow",
    "filled"
  >;

  /**
   * Keywords field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Comma-separated keywords for SEO
   * - **API ID Path**: post.keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  keywords: prismic.KeyTextField;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;

export type AllDocumentTypes =
  | CategoryDocument
  | HomepageDocument
  | PageDocument
  | PostDocument;

/**
 * Primary content in *CodeBlock → Default → Primary*
 */
export interface CodeBlockSliceDefaultPrimary {
  /**
   * Language field in *CodeBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select programming language
   * - **Default Value**: javascript
   * - **API ID Path**: code_block.default.primary.language
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  language: prismic.SelectField<
    | "javascript"
    | "typescript"
    | "jsx"
    | "tsx"
    | "python"
    | "java"
    | "c"
    | "cpp"
    | "csharp"
    | "php"
    | "ruby"
    | "go"
    | "rust"
    | "kotlin"
    | "swift"
    | "dart"
    | "bash"
    | "shell"
    | "powershell"
    | "sql"
    | "graphql"
    | "html"
    | "css"
    | "scss"
    | "sass"
    | "less"
    | "xml"
    | "json"
    | "yaml"
    | "toml"
    | "markdown"
    | "latex"
    | "plaintext",
    "filled"
  >;

  /**
   * Code field in *CodeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Paste your code here...
   * - **API ID Path**: code_block.default.primary.code
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  code: prismic.KeyTextField;

  /**
   * Filename (optional) field in *CodeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., app.js
   * - **API ID Path**: code_block.default.primary.filename
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  filename: prismic.KeyTextField;

  /**
   * Show Line Numbers field in *CodeBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: code_block.default.primary.show_line_numbers
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_line_numbers: prismic.BooleanField;
}

/**
 * Default variation for CodeBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default code block
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CodeBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CodeBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CodeBlock*
 */
type CodeBlockSliceVariation = CodeBlockSliceDefault;

/**
 * CodeBlock Shared Slice
 *
 * - **API ID**: `code_block`
 * - **Description**: Code block with syntax highlighting
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CodeBlockSlice = prismic.SharedSlice<
  "code_block",
  CodeBlockSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hero title
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Hero description
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section for pages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Rich text content...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default rich text variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: Rich text content with formatting
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CategoryDocument,
      CategoryDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PostDocument,
      PostDocumentData,
      PostDocumentDataSlicesSlice,
      AllDocumentTypes,
      CodeBlockSlice,
      CodeBlockSliceDefaultPrimary,
      CodeBlockSliceVariation,
      CodeBlockSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
