// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  code_block: dynamic(() => import("./CodeBlock")),
  rich_text: dynamic(() => import("./RichText")),
};
