// Code generated by Slice Machine. DO NOT EDIT.

// Import components directly to avoid DYNAMIC_SERVER_USAGE error
import CodeBlock from './CodeBlock'
import RichText from './RichText'

export const components = {
  code_block: CodeBlock,
  rich_text: RichText,
}
